import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { InterviewGuide } from '../types';

export const exportGuideToPDF = (guide: InterviewGuide) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;

  // Helper for adding text with word wrap
  const addText = (text: string, fontSize: number, isBold = false, color = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(color[0], color[1], color[2]);
    
    const lines = doc.splitTextToSize(text, pageWidth - (margin * 2));
    
    // Check if we need a new page
    if (yPos + (lines.length * (fontSize * 0.5)) > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.text(lines, margin, yPos);
    yPos += (lines.length * (fontSize * 0.5)) + 5;
  };

  // Helper for horizontal line
  const addLine = () => {
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 10;
  };

  // Branding
  doc.setFontSize(10);
  doc.setTextColor(0, 119, 182); // ocean-primary
  doc.text('Generated by RoleIntel', pageWidth - margin - 40, 10);

  // Title
  addText(`Interview Guide: ${guide.jobTitle}`, 22, true, [3, 4, 94]); // ocean-deep
  addText(`Company: ${guide.companyName}`, 14, true, [0, 119, 182]); // ocean-primary
  addLine();

  // Section: Overview
  addText('1. Strategic Overview', 16, true, [3, 4, 94]);
  yPos += 2;
  
  addText('Core Requirements:', 12, true, [3, 4, 94]);
  guide.keyRequirements.forEach(req => {
    addText(`• ${req}`, 10, false, [3, 4, 94]);
  });
  yPos += 5;

  addText('Top Skills to Highlight:', 12, true, [3, 4, 94]);
  addText(guide.topSkills.join(', '), 10, false, [13, 148, 136]); // success-teal
  yPos += 10;

  // Section: Narration Strategy
  addText('2. Narration Strategy', 16, true, [3, 4, 94]);
  yPos += 2;
  addText('The Core Story:', 12, true, [3, 4, 94]);
  addText(guide.narrationStrategy.coreStory, 10, false, [3, 4, 94]);
  yPos += 3;
  addText('Elevator Pitch:', 12, true, [3, 4, 94]);
  addText(`"${guide.narrationStrategy.elevatorPitch}"`, 10, true, [0, 119, 182]);
  yPos += 10;

  // Section: Company Intel
  addText('3. Company Intel', 16, true, [3, 4, 94]);
  yPos += 2;
  addText('Mission & Values:', 12, true, [3, 4, 94]);
  guide.companyInsights.missionAndValues.forEach(mv => {
    addText(`• ${mv}`, 10, false, [3, 4, 94]);
  });
  yPos += 3;
  addText('Culture Vibe:', 12, true, [3, 4, 94]);
  addText(guide.companyInsights.cultureVibe, 10, true, [3, 4, 94]);
  yPos += 10;

  // Section: Interview Questions
  doc.addPage();
  yPos = 20;
  addText('4. Interview Questions & Insider Tips', 16, true, [3, 4, 94]);
  yPos += 5;

  const categories = ['Behavioral', 'Technical', 'Role-Specific', 'Cultural'];
  const categoryColors: Record<string, [number, number, number]> = {
    'Behavioral': [0, 119, 182], // ocean-primary
    'Technical': [13, 148, 136], // success-teal
    'Role-Specific': [3, 4, 94],  // ocean-deep
    'Cultural': [0, 180, 216]    // ocean-accent
  };

  categories.forEach(cat => {
    const questions = guide.interviewQuestions.filter(q => q.category === cat);
    if (questions.length > 0) {
      addText(`${cat} Questions`, 14, true, categoryColors[cat]);
      yPos += 2;
      
      const tableData = questions.map((q, idx) => [
        `Q${idx + 1}`,
        `${q.question}\n\nSuggested Answer: ${q.suggestedAnswer}\n\nInsider Tip: ${q.insiderTip}`
      ]);

      autoTable(doc, {
        startY: yPos,
        head: [['#', 'Question & Guidance']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: categoryColors[cat] },
        columnStyles: {
          0: { cellWidth: 15 },
          1: { cellWidth: 'auto' }
        },
        margin: { left: margin, right: margin },
        didDrawPage: (data: any) => {
          yPos = data.cursor.y + 10;
        }
      });
      
      yPos = (doc as any).lastAutoTable.finalY + 10;
    }
  });

  // Section: Resume Analysis
  if (guide.resumeAnalysis) {
    doc.addPage();
    yPos = 20;
    addText('5. Resume Gap Analysis', 16, true, [3, 4, 94]);
    yPos += 5;

    addText('Strengths:', 12, true, [13, 148, 136]); // success-teal
    guide.resumeAnalysis.strengths.forEach(s => addText(`• ${s}`, 10, false, [3, 4, 94]));
    yPos += 3;

    addText('Weaknesses / Gaps:', 12, true, [0, 119, 182]); // ocean-primary
    guide.resumeAnalysis.weaknesses.forEach(w => addText(`• ${w}`, 10, false, [3, 4, 94]));
    yPos += 3;

    addText('Focus Areas:', 12, true, [3, 4, 94]);
    guide.resumeAnalysis.areasToFocus.forEach(f => addText(`• ${f}`, 10, false, [3, 4, 94]));
    yPos += 3;

    addText('Tailoring Advice:', 12, true, [3, 4, 94]);
    addText(guide.resumeAnalysis.tailoringAdvice, 10, false, [3, 4, 94]);
  }

  // Save the PDF
  doc.save(`${guide.companyName.replace(/\s+/g, '_')}_Interview_Guide.pdf`);
};
